### ISSUE TITLE
Accuracy of pointer

### ISSUE THREAD

**Issue by Youngei402tw** [marcowindt/WiiMoteDSU#7]
So I was trying to get this working on my dolphin, everything went well except the accuracy for the wii pointer are really laggy and bad, but when I tried using motionsource apk, and it runs smoothly in dolphin, I also tried pad test with your app, and the pad was upside down, and wasn't quite following my movement. In wii games, the pointer was either not following my movement, or going everywhere.  And also I cannot see the pad in pad test, if accelerometer was turned off, can you tell us what's the best configuration for your in-app settings? Whether to turn the acc on or off, and the invert or not. And btw will a nutchuck feature be implemented in later development?

**Comment by Youngei402tw** [comment]
I also want to point out that the motionsource is working great, but it only provide motion, not buttons control, I wish the motionsource feature can be implemented into your app

**Comment by marcowindt** [comment]
The issue with the pointer is fixed in 2fd64fb1ecbdfe2cb51f189064cb09120ef8268f.
Also, right now when you press "Reset to default" on the settings screen it will reset the settings to which should be the best configuration to use it.

I agree it would be cool to also integrate features of the nunchunk, like the thumbstick. 
Maybe have some kind of button layouts as used in [DolphiniOS](https://dolphinios.oatmealdome.me/)?

**Comment by Youngei402tw** [comment]
Maybe can implement a nutchuck with an other phone, hence create the feeling of holding the wiimote and nutchuck in both hands, and im also very interested in your project, im a Computer Science student, I have some knowledge about c/c++/python programming, if there is anything i can help pls let me know, can contact me through this email youngei402tw@gmail.com, or we can discuss via discord or any other apps you prefer, do let me know if there is anything i could help, ill try my best and also sorry for the bad English, I'm Taiwanese.
